DATABASE_CONNECTION_STRING = "mysql+pymysql://assistant:6548@10.0.0.52/elite"

STATION_TYPES = [
    "Coriolis",
    "Asteroid Base",
    "Ocellus",
    "Orbis",
    "Commercial Outpost",
    "Industrial Outpost",
    "Criminal Outpost",
    "Civilian Outpost",
    "Scientific Outpost",
    "Military Outpost",
    "Satellite",
    "Communication Station",
    "Space Farm",
    "Pirate Base",
    "Mining Outpost",
    "Relay Station",
    "Military",
    "Security Station",
    "Government",
    "Medical",
    "Research Station",
    "Tourist",
    "Bar",
    "Outpost",
    "Port",
    "Agriculture Tier 1",
    "Agriculture Tier 2",
    "Extraction Tier 1",
    "Extraction Tier 2",
    "Industrial Tier 1",
    "Industrial Tier 2",
    "Military Tier 1",
    "Military Tier 2",
    "Research Bio Tier 1",
    "Research Bio Tier 2",
    "Tourism Tier 1",
    "Tourism Tier 2",
    "Extraction",
    "Civilian",
    "Exploration",
    "Scientific",
    "Refinery",
    "High Tech",
    "Industrial",
]

MATERIAL_LISTS = [
    "Aluminium",
    "Ceramic Composites",
    "CMM Composite",
    "Computer components",
    "Copper",
    "Food cartridges",
    "Fruit and vegetables",
    "Insulating membrane",
    "Liquid oxygen",
    "Medical diagnostic equipment",
    "Non-lethal weapons",
    "Polymers",
    "Power generators",
    "Semiconductors",
    "Steel",
    "Superconductors",
    "Titanium",
    "Water",
    "Water purifiers",
]

# SurfaceStation
WHAT_MAKES_THIS = {
    "Aluminium": ["Refinery"],
    "Ceramic Composites": ["Refinery/CraterOutpost"],
    "CMM Composite": ["Refinery/CraterOutpost"],
    "Computer Components": ["Industrial"],
    "Copper": ["Refinery"],
    "Food Cartridges": ["Industrial"],
    "Fruit and Vegetables": ["Agri"],
    "Insulating Membrane": ["Refinery/Starport"],
    "Liquid Oxygen": ["Refinery"],
    "Medical Diagnostic Equipment": ["HighTech"],
    "Non-Lethal Weapons": ["HighTech", "Military"],
    "Polymers": ["Refinery"],
    "Power Generators": ["Industrial"],
    "Semiconductors": ["Refinery"],
    "Steel": ["Refinery"],
    "Superconductors": ["Refinery"],
    "Titanium": ["Refinery"],
    "Water": ["Agri", "Extraction/CraterOutpost"],
    "Water Purifiers": ["Industrial"],
}
